name: Build and Upload Artifact

on:
  push: 
    tags:
      - 'v*'  # This means the workflow only runs when you push a tag like v1.0, v2.1 etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build a file
        run: |
          mkdir output
          echo "This is a test file from GitHub Actions!" > output/test.txt
          zip -r build.zip output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-archive
          path: build.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
